trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
  # Docker
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'GitHub Docker Registry'
        repository: 'Immersed.dive.shop'
        command: 'push'
        # Build a Docker image
        # https://docs.microsoft.com/azure/devops/pipelines/languages/docker