services:
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ConnectionStrings:DefaultConnectionString=Server=docker-sqlserver;Database=immersedDiveShop;User Id=sa;Password=smudge@9852;TrustServerCertificate=True
      - ConnectionStrings:MigrationsConnectionString=Server=docker-sqlserver;Database=master;User Id=sa;Password=smudge@9852;TrustServerCertificate=True
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - docker-sqlserver    
      
  docker-sqlserver:
    container_name: docker-sqlserver-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=smudge@9852
    volumes:
      - /mnt/c/data:/var/opt/mssql/data
    ports:
      - 1466:1433

  cachedData:
    image: redis
    expose:
      - "6379"      
volumes:
  sssvolume:    
  
  
      



    